setwd('/Users/ivan/Work_directory/FICO/Helping-Santas-Helpers/')
setwd('C:/Users/Ivan.Liuyanfeng/Desktop/Data_Mining_Work_Space/FICO/Helping-Santas-Helpers')
gc(); rm(list=ls())
# toys_rev2 <- read.csv('toys_rev2.csv')
# save(toys_rev2,file='data/toys_rev2.RData')
# sampleSubmission_rev2 <- read.csv('sampleSubmission_rev2.csv')
# save(sampleSubmission_rev2,file='data/sampleSubmission_rev2.RData')
load('data/toys_rev2.RData')
source("hours.R")
elf <- data.frame(elfid = 1:900)
